allowed:
  origins: http://localhost:3000

spring:


  datasource:
    url: jdbc:postgresql://dpg-co986gdjm4es73aqpvkg-a.oregon-postgres.render.com:5432/postgress_5utu
    username: postgress
    password: jQlyhL4AVgmrzPNlWNUDE0FNDW83yM33
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
jwt:
  security:
    key: fGI9opiU1LvF18BRMZBJD3tFCy4QtSjIzh2X7rvbKKb2HqTZrreiQC9EzMqiosmq

artisan_finds:
  eskiz:
    sms:
      token: oDWIaq4FkvjmGwqTjbXSstNBuGcm3EgQGp8pL2Ys8zUEkR12nBG0eSCxB6iVgmQ7

#logging:
#  level:
#    org:
#      springframework:
#        security: trace
server:
  port: 8082
